import React, { useState } from "react";
import {
  Clock,
  Trash2,
  Copy,
  Check,
  Search,
  ExternalLink,
  MessageSquare,
  FileText,
  Video,
  Sparkles,
  ImageIcon,
  Share2,
  Languages,
  X,
  Play,
  Download,
  FileDown,
} from "lucide-react";
import { HistoryItem, HistoryType } from "../types";
import { deleteHistoryItem, clearAllHistory } from "../lib/storage";

interface HistoryViewProps {
  history: HistoryItem[];
  onRefreshHistory: () => void;
  onNavigateToTab: (tab: any) => void;
}

export const HistoryView: React.FC<HistoryViewProps> = ({
  history,
  onRefreshHistory,
  onNavigateToTab,
}) => {
  const [filter, setFilter] = useState<string>("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedItem, setSelectedItem] = useState<HistoryItem | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (message: string) => {
    setToastMessage(message);
    setTimeout(() => {
      setToastMessage((prev) => (prev === message ? null : prev));
    }, 2800);
  };

  const categories = [
    { id: "all", label: "All Items" },
    { id: "video", label: "AI Videos", icon: Video },
    { id: "chat", label: "Chats", icon: MessageSquare },
    { id: "script", label: "Scripts", icon: FileText },
    { id: "thumbnail", label: "Thumbnails", icon: ImageIcon },
    { id: "prompt_improver", label: "Prompts", icon: Sparkles },
    { id: "caption", label: "Captions", icon: Share2 },
    { id: "translate", label: "Translations", icon: Languages },
  ];

  const filteredItems = history.filter((item) => {
    const matchesFilter = filter === "all" || item.type === filter;
    const matchesSearch =
      searchQuery.trim() === "" ||
      item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.content.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (item.subtitle && item.subtitle.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesFilter && matchesSearch;
  });

  const handleCopy = (text: string, id: string, label = "Copied to clipboard!") => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    showToast(label);
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleShare = async (item: HistoryItem, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    const shareData = {
      title: item.title,
      text: `${item.title}\n\n${item.content}\n\nGenerated with Sanaullah AI`,
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
        showToast("Shared successfully!");
        return;
      } catch (err: any) {
        if (err.name === "AbortError") {
          return;
        }
      }
    }

    // Fallback: Copy content to clipboard
    handleCopy(shareData.text, item.id, "Content copied to clipboard for sharing!");
  };

  const downloadTextFile = (filename: string, text: string) => {
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const formatItemForExport = (item: HistoryItem): string => {
    const dateStr = new Date(item.timestamp).toLocaleString();
    return [
      `==================================================`,
      `SANAULLAH AI - EXPORTED GENERATION`,
      `==================================================`,
      `Title: ${item.title}`,
      `Type: ${item.type}`,
      `Date: ${dateStr}`,
      item.subtitle ? `Details: ${item.subtitle}` : "",
      item.metadata?.videoUrl ? `Video URL: ${item.metadata.videoUrl}` : "",
      `--------------------------------------------------`,
      `CONTENT:`,
      item.content,
      `--------------------------------------------------`,
      `Generated by Sanaullah AI Assistant`,
      `Socials: YouTube @SanaullahAI | TikTok @sanaullahai`,
      `==================================================`,
    ]
      .filter(Boolean)
      .join("\n");
  };

  const handleExportSingle = (item: HistoryItem, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    const sanitizedTitle = item.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 35) || "creation";
    const filename = `sanaullah-ai-${sanitizedTitle}.txt`;
    const text = formatItemForExport(item);
    downloadTextFile(filename, text);
    showToast(`Exported "${item.title.slice(0, 24)}" as text file`);
  };

  const handleExportAll = () => {
    if (filteredItems.length === 0) return;

    const currentCategoryLabel =
      categories.find((c) => c.id === filter)?.label || "All Items";

    const header = [
      `==================================================`,
      `SANAULLAH AI - EXPORTED GENERATION ARCHIVE`,
      `Category Filter: ${currentCategoryLabel}`,
      `Total Creations Exported: ${filteredItems.length}`,
      `Export Timestamp: ${new Date().toLocaleString()}`,
      `==================================================\n\n`,
    ].join("\n");

    const body = filteredItems
      .map((item, index) => {
        const dateStr = new Date(item.timestamp).toLocaleString();
        return [
          `--------------------------------------------------`,
          `[Item #${index + 1}] ${item.title}`,
          `Category: ${item.type} | Date: ${dateStr}`,
          item.subtitle ? `Details: ${item.subtitle}` : "",
          item.metadata?.videoUrl ? `Video URL: ${item.metadata.videoUrl}` : "",
          `--------------------------------------------------`,
          item.content,
          `\n`,
        ]
          .filter(Boolean)
          .join("\n");
      })
      .join("\n");

    const footer = `\n==================================================\nEnd of Sanaullah AI Export Archive (${filteredItems.length} items)\n==================================================`;
    const filename = `sanaullah-ai-history-${filter}-${new Date().toISOString().slice(0, 10)}.txt`;

    downloadTextFile(filename, header + body + footer);
    showToast(`Exported ${filteredItems.length} creations as ${filename}`);
  };

  const handleDelete = (id: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    deleteHistoryItem(id);
    onRefreshHistory();
    if (selectedItem?.id === id) setSelectedItem(null);
    showToast("History item deleted");
  };

  const handleClearAll = () => {
    if (window.confirm("Are you sure you want to delete all saved generation history?")) {
      clearAllHistory();
      onRefreshHistory();
      setSelectedItem(null);
      showToast("All history cleared");
    }
  };

  const getIconForType = (type: HistoryType) => {
    switch (type) {
      case "video":
        return Video;
      case "chat":
        return MessageSquare;
      case "script":
        return FileText;
      case "thumbnail":
        return ImageIcon;
      case "prompt_improver":
        return Sparkles;
      case "caption":
      case "hashtags":
        return Share2;
      case "translate":
        return Languages;
      default:
        return Clock;
    }
  };

  return (
    <div id="history-view-container" className="space-y-4 pb-24 max-w-3xl mx-auto">
      {/* Toast Notification */}
      {toastMessage && (
        <div
          id="history-toast-notification"
          className="fixed bottom-20 left-1/2 -translate-x-1/2 z-50 bg-[#151c2e] text-slate-100 border border-cyan-500/40 px-4 py-2 rounded-xl shadow-xl flex items-center space-x-2 text-xs font-semibold backdrop-blur-md"
        >
          <Check className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Header with Title & Action Buttons */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-xl sm:text-2xl font-extrabold text-white tracking-tight flex items-center space-x-2">
            <Clock className="w-5 h-5 text-cyan-400" />
            <span>My History</span>
          </h1>
          <p className="text-xs text-slate-400">
            {history.length} saved creation{history.length === 1 ? "" : "s"} stored locally in your browser.
          </p>
        </div>

        {history.length > 0 && (
          <div className="flex items-center space-x-2">
            {/* Export All Button */}
            <button
              id="history-export-all-btn"
              onClick={handleExportAll}
              disabled={filteredItems.length === 0}
              className="flex items-center space-x-1.5 text-xs text-cyan-300 hover:text-cyan-100 bg-cyan-500/10 hover:bg-cyan-500/20 disabled:opacity-50 disabled:cursor-not-allowed px-3 py-1.5 rounded-lg border border-cyan-500/30 transition shadow-sm"
              title="Export saved items as a text file"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export ({filteredItems.length}) .txt</span>
            </button>

            {/* Clear History Button */}
            <button
              id="history-clear-all-btn"
              onClick={handleClearAll}
              className="flex items-center space-x-1 text-xs text-rose-400 hover:text-rose-300 bg-rose-500/10 hover:bg-rose-500/20 px-3 py-1.5 rounded-lg border border-rose-500/20 transition"
              title="Delete all saved items"
            >
              <Trash2 className="w-3.5 h-3.5" />
              <span>Clear</span>
            </button>
          </div>
        )}
      </div>

      {/* Search Input */}
      <div className="relative">
        <Search className="w-4 h-4 text-slate-500 absolute left-3.5 top-1/2 -translate-y-1/2" />
        <input
          id="history-search-input"
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Search saved scripts, prompts, videos..."
          className="w-full bg-[#111726] text-slate-100 text-xs sm:text-sm pl-10 pr-4 py-2.5 rounded-xl border border-slate-800 focus:outline-none focus:border-cyan-500/60"
        />
        {searchQuery && (
          <button
            id="history-search-clear-btn"
            onClick={() => setSearchQuery("")}
            className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-200"
          >
            <X className="w-4 h-4" />
          </button>
        )}
      </div>

      {/* Filter Category Pills */}
      <div className="flex items-center space-x-1.5 overflow-x-auto no-scrollbar py-1">
        {categories.map((c) => {
          const isActive = filter === c.id;
          return (
            <button
              key={c.id}
              id={`history-category-tab-${c.id}`}
              onClick={() => setFilter(c.id)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition ${
                isActive
                  ? "bg-cyan-500 text-white shadow-sm"
                  : "bg-[#111726] text-slate-400 hover:text-slate-200 border border-slate-800"
              }`}
            >
              {c.label}
            </button>
          );
        })}
      </div>

      {/* History Items List */}
      {filteredItems.length === 0 ? (
        <div id="history-empty-state" className="p-8 text-center rounded-2xl bg-[#111726]/60 border border-slate-800 space-y-3">
          <Clock className="w-10 h-10 text-slate-600 mx-auto" />
          <h3 className="text-sm font-bold text-slate-300">
            {searchQuery ? "No matching history found" : "No creations saved yet"}
          </h3>
          <p className="text-xs text-slate-500 max-w-sm mx-auto">
            {searchQuery
              ? "Try adjusting your search query or clear the filter."
              : "Generate scripts, AI videos, thumbnail prompts, or chats to see them saved here automatically."}
          </p>
          {!searchQuery && (
            <button
              id="history-explore-tools-btn"
              onClick={() => onNavigateToTab("tools")}
              className="inline-flex items-center space-x-1 text-xs font-semibold text-cyan-400 hover:text-cyan-300 pt-2"
            >
              <span>Explore AI Tools</span>
              <ExternalLink className="w-3.5 h-3.5 ml-0.5" />
            </button>
          )}
        </div>
      ) : (
        <div className="space-y-2.5">
          {filteredItems.map((item) => {
            const Icon = getIconForType(item.type);
            const dateStr = new Date(item.timestamp).toLocaleDateString(undefined, {
              month: "short",
              day: "numeric",
              hour: "2-digit",
              minute: "2-digit",
            });

            return (
              <div
                key={item.id}
                id={`history-item-card-${item.id}`}
                onClick={() => setSelectedItem(item)}
                className="group cursor-pointer p-4 rounded-xl bg-[#111726] hover:bg-[#161f33] border border-slate-800 hover:border-slate-700 transition space-y-2 shadow-sm"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center space-x-2 min-w-0">
                    <div className="w-7 h-7 rounded-lg bg-slate-800 flex items-center justify-center text-cyan-400 shrink-0">
                      <Icon className="w-3.5 h-3.5" />
                    </div>
                    <div className="min-w-0">
                      <h4 className="text-xs sm:text-sm font-bold text-slate-100 group-hover:text-cyan-300 transition-colors line-clamp-1">
                        {item.title}
                      </h4>
                      <div className="flex items-center space-x-2 text-[11px] text-slate-400">
                        {item.subtitle && <span>{item.subtitle}</span>}
                        <span>•</span>
                        <span>{dateStr}</span>
                      </div>
                    </div>
                  </div>

                  {/* Actions: Share, Export .txt, Copy & Delete */}
                  <div className="flex items-center space-x-1 opacity-85 sm:opacity-75 group-hover:opacity-100 shrink-0">
                    <button
                      id={`history-item-share-${item.id}`}
                      onClick={(e) => handleShare(item, e)}
                      className="p-1.5 text-slate-400 hover:text-cyan-400 rounded-lg hover:bg-slate-800 transition"
                      title="Share content or copy link"
                    >
                      <Share2 className="w-4 h-4" />
                    </button>

                    <button
                      id={`history-item-export-${item.id}`}
                      onClick={(e) => handleExportSingle(item, e)}
                      className="p-1.5 text-slate-400 hover:text-cyan-400 rounded-lg hover:bg-slate-800 transition"
                      title="Export as .txt text file"
                    >
                      <Download className="w-4 h-4" />
                    </button>

                    <button
                      id={`history-item-copy-${item.id}`}
                      onClick={(e) => {
                        e.stopPropagation();
                        handleCopy(item.content, item.id);
                      }}
                      className="p-1.5 text-slate-400 hover:text-cyan-400 rounded-lg hover:bg-slate-800 transition"
                      title="Copy content"
                    >
                      {copiedId === item.id ? (
                        <Check className="w-4 h-4 text-emerald-400" />
                      ) : (
                        <Copy className="w-4 h-4" />
                      )}
                    </button>

                    <button
                      id={`history-item-delete-${item.id}`}
                      onClick={(e) => handleDelete(item.id, e)}
                      className="p-1.5 text-slate-400 hover:text-rose-400 rounded-lg hover:bg-slate-800 transition"
                      title="Delete item"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </div>

                {/* Content snippet */}
                <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed bg-[#0c111c] p-2.5 rounded-lg border border-slate-800/80">
                  {item.content}
                </p>

                {item.metadata?.videoUrl && (
                  <div className="flex items-center space-x-1.5 text-xs text-pink-400 font-semibold pt-1">
                    <Play className="w-3 h-3 fill-pink-400" />
                    <span>AI Video Attached</span>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      )}

      {/* Detail Modal */}
      {selectedItem && (
        <div
          id="history-detail-modal-backdrop"
          className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4"
        >
          <div
            id="history-detail-modal"
            className="bg-[#111726] border border-slate-700 rounded-2xl max-w-lg w-full max-h-[85vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-150"
          >
            {/* Modal Header */}
            <div className="flex items-center justify-between p-4 border-b border-slate-800 bg-[#0e1422]">
              <div className="flex items-center space-x-2 min-w-0 pr-2">
                <span className="text-xs uppercase font-bold px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/30 shrink-0">
                  {selectedItem.type}
                </span>
                <h3 className="text-sm font-bold text-slate-100 truncate">
                  {selectedItem.title}
                </h3>
              </div>
              <button
                id="history-modal-close-btn"
                onClick={() => setSelectedItem(null)}
                className="p-1 text-slate-400 hover:text-white rounded-lg hover:bg-slate-800 shrink-0"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Body */}
            <div className="flex-1 overflow-y-auto p-4 space-y-4">
              {selectedItem.metadata?.videoUrl && (
                <div className="rounded-xl overflow-hidden bg-black aspect-video border border-slate-800">
                  <video
                    src={selectedItem.metadata.videoUrl}
                    controls
                    className="w-full h-full object-contain"
                  />
                </div>
              )}

              <div className="space-y-1">
                <div className="flex items-center justify-between text-[11px] font-bold text-slate-400 uppercase">
                  <span>Content / Prompt</span>
                  <span>{new Date(selectedItem.timestamp).toLocaleString()}</span>
                </div>
                <div className="p-3.5 rounded-xl bg-[#0a0f19] border border-slate-800 text-xs sm:text-sm text-slate-200 whitespace-pre-wrap leading-relaxed select-all">
                  {selectedItem.content}
                </div>
              </div>
            </div>

            {/* Modal Footer with Share, Export, Copy and Delete */}
            <div className="p-3.5 border-t border-slate-800 bg-[#0e1422] flex flex-wrap gap-2 items-center justify-between">
              <button
                id="history-modal-delete-btn"
                onClick={() => handleDelete(selectedItem.id)}
                className="flex items-center space-x-1 text-xs text-rose-400 hover:text-rose-300 font-semibold px-3 py-2 rounded-lg hover:bg-rose-500/10 transition"
              >
                <Trash2 className="w-3.5 h-3.5" />
                <span>Delete</span>
              </button>

              <div className="flex items-center flex-wrap gap-2">
                <button
                  id="history-modal-share-btn"
                  onClick={() => handleShare(selectedItem)}
                  className="flex items-center space-x-1.5 text-xs font-semibold text-slate-200 hover:text-white bg-slate-800 hover:bg-slate-700 px-3 py-2 rounded-xl border border-slate-700 transition"
                  title="Share or copy content"
                >
                  <Share2 className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Share</span>
                </button>

                <button
                  id="history-modal-export-btn"
                  onClick={() => handleExportSingle(selectedItem)}
                  className="flex items-center space-x-1.5 text-xs font-semibold text-cyan-300 hover:text-cyan-200 bg-cyan-500/10 hover:bg-cyan-500/20 px-3 py-2 rounded-xl border border-cyan-500/30 transition"
                  title="Export this content as a .txt file"
                >
                  <Download className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Export .txt</span>
                </button>

                <button
                  id="history-modal-copy-btn"
                  onClick={() => handleCopy(selectedItem.content, "modal_copy")}
                  className="flex items-center space-x-1.5 text-xs font-semibold text-white bg-cyan-600 hover:bg-cyan-500 px-3.5 py-2 rounded-xl shadow-md transition"
                >
                  {copiedId === "modal_copy" ? (
                    <>
                      <Check className="w-4 h-4 text-white" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      <span>Copy</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

